[project]
name = "calibration-search"
version = "0.1.0"
description = ""
authors = [
    {name = "Theviyanthan Krishnamohan",email = "theviyanthan@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
]

[project.scripts]
analyse = "calibration_search.analysis:main"
run-analysis = "calibration_search.analysis:main"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
